export const SEAT_OFFSET = 35;      // cm from table edge to seat centre
export const SEAT_RADIUS = 20;      // cm, drawn radius of a seat circle
export const GRID_MINOR = 100;      // cm
export const GRID_MAJOR = 500;      // cm
export const GRID_SNAP_STEP = 25;   // cm
export const SNAP_PX = 8;           // screen px, divided by stage scale before use
export const SNAP_NEIGHBOUR_RANGE = 300; // cm
export const SEAT_DROP_RANGE = 40;  // cm
export const NUDGE = 10;            // cm
export const NUDGE_LARGE = 100;     // cm
export const DUPLICATE_OFFSET = 30; // cm
export const ROTATION_SNAP = 15;    // degrees while Shift is held
export const HISTORY_CAP = 100;
export const AUTOSAVE_MS = 1000;
export const LS_KEY = 'setting:doc:v1';
export const RULER_SIZE = 28;       // px
export const MIN_SCALE = 0.05;
export const MAX_SCALE = 6;
export const GRID_HIDE_BELOW = 0.25;
export const SEAT_INITIALS_ABOVE = 0.6;
export const SEAT_NAMES_ABOVE = 1.0;
export const CM_PER_FOOT = 30.48;
